### PR TITLE
Avoid using type declaration file in import

### PR DESCRIPTION
**Pull request by Miljoen**
This commit fixes an error whilst compiling my TS project 🎉.
Hopefully others can benefit from this fix as well.

It is advised to not import `@types/<package>` directly, as the error message mentions.

Command in my pipeline: `npx tsc --outDir dist`

```
❯ npx tsc --outDir dist
node_modules/graphql-upload-minimal/public/index.d.ts:5:32 - error TS6137: Cannot import type declaration files. Consider importing 'express' instead of '@types/express'.

5 import { RequestHandler } from "@types/express";
                                 ~~~~~~~~~~~~~~~~

node_modules/graphql-upload-minimal/public/index.d.ts:6:58 - error TS2307: Cannot find module '@types/koa' or its corresponding type declarations.

6 import { DefaultContext, DefaultState, Middleware } from "@types/koa";
                                                           ~~~~~~~~~~~~

node_modules/graphql-upload-minimal/public/index.d.ts:6:58 - error TS6137: Cannot import type declaration files. Consider importing 'koa' instead of '@types/koa'.

6 import { DefaultContext, DefaultState, Middleware } from "@types/koa";
                                                           ~~~~~~~~~~~~


Found 3 errors in the same file, starting at: node_modules/graphql-upload-minimal/public/index.d.ts:5
```

### CODE REVIEW

**Comment by Miljoen** [comment]
Small side note:
I did have to install 
```
"@types/express": "^4.17.13",
"@types/koa": "^2.13.5",
```
as dev dependencies in my project.

Perhaps it is a good idea to make these not optional in the package's peer dependencies?

**Comment by koresar** [comment]
Hello.
If you take a look at the history of the file you changed you'll see that you returned it to the state it was few weeks ago. :)))

We do not want this little library to bring TWO HUGE FRAMEWORKS with it as dependencies.
Please, use `any` or any other TS ignoring tricks.

Or, submit a new PR which:
a) does not increase `node_modules` of the packages users,
b) fixes all things you need.

For now, I'm closing this pull request. Feel free to discuss further.

**Comment by JJWesterkamp** [comment]
This change does not instruct `npm` to install `express` or `koa`. It's just that Typescript does not understand `@types` imports, because that is not how these packages are meant to be used. The `@types` namespace is just there to group types packages in the npm registry. This namespace is universally known as a so-called _typeroot_ where the typescript compiler can start looking for type declarations for particular packages, `express` and `koa` in this case.

The `package.json` file of this module is always leading. If we do:

```
cd ~
mkdir test
cd test
npm init
npm install git+https://github.com/Miljoen/graphql-upload-minimal.git#master
```

... and see if `koa` or `express` are in the dependency tree, we get `(empty)`:

```
$ npm ls koa                                                                                                                                                                            ─╯
test@1.0.0 /Users/xxx/test
└── (empty)

$ npm ls express                                                                                                                                                                             ─╯
test@1.0.0 /Users/xxx/test
└── (empty)
```

**Comment by koresar** [comment]
Thanks for the excellent explanation. I'll see what I can do.

File: public/index.d.ts [hunk 1]
```diff
@@ -2,8 +2,8 @@ import { IncomingMessage, ServerResponse } from "http";
 import { GraphQLScalarType } from "graphql";
 import { ReadStream } from "fs";
 
-import { RequestHandler } from "@types/express";
-import { DefaultContext, DefaultState, Middleware } from "@types/koa";
+import { RequestHandler } from "express";
```
Comment (koresar) [inline public/index.d.ts:5]: Can we `import type ...` instead of `import` ?
Asking for a friend. :)

**Review by koresar — CHANGES_REQUESTED** [review]

File: public/index.d.ts (hunk 1 above)
Comment (Miljoen) [reply public/index.d.ts]: Added!

Thank you for reopening this PR.

**Comment by Miljoen** [comment]
I would like to point you one more time to my side note:
```
❯ npx tsc --outDir dist
node_modules/graphql-upload-minimal/public/index.d.ts:6:58 - error TS2307: Cannot find module 'koa' or its corresponding type declarations.

6 import { DefaultContext, DefaultState, Middleware } from "koa";
                                                           ~~~~~


Found 1 error in node_modules/graphql-upload-minimal/public/index.d.ts:6
```

In order to fix this for my project (express app), I had to `npm i -D @types/koa` (in my own project that does _not_ use koa)

Both  `@types/express` and `@types/koa` need to be present to resolve the types.

I think it is advisable to:

- Install both `@types/express` and `@types/koa` as dev deps OR
- Split up the module and resolve these independently

**Review by koresar — APPROVED** [review]

**Comment by koresar** [comment]
Published. See if it works in v1.5.4
https://github.com/flash-oss/graphql-upload-minimal/releases/tag/v1.5.4

**Comment by Miljoen** [comment]
Just tested, v1.5.4 works great for me!
